CHANGELOG.md
=> Update CHANGELOG to match current unreleased changes

CHANGELOG.md, internal/commands/server/stop.go
=> Public beta version (0.5.0)

internal/core/bootstrap.go
=> fix(root): use default cobra behavious when called

CHANGELOG.md
=> CHANGELOG: Add "Unreleased" section & fix links

cmd/doc-gen/main.go, cmd/upctl/main.go, internal/commands/runcommand.go, internal/core/core.go, internal/core/core_test.go
We need to validate input flags and environment variables
=> test: input configs

internal/commands/storage/import.go
=> chore(storage): return proper error on import failure

internal/commands/ipaddress/show.go, internal/commands/network/list.go, internal/commands/network/list_test.go, internal/commands/network/show.go, internal/commands/server/list.go, internal/commands/server/show.go
=> Add colors to some missing UUIDs

internal/config/config.go, internal/config/config_test.go, internal/core/core_test.go
=> fix(config/load): improve error message when loading invalid YAML

.github/workflows/publish.yml, .goreleaser.yml, Dockerfile.goreleaser
Use Goreleaser to build & deploy Docker images to Docker Hub
=> Goreleaser: new deploy for Docker images

README.md
The support for current directory was removed some time ago.
=> Remove mention of current directory for config

.github/workflows/test.yml
=> chore(gh/workflow): filter test triggering

.goreleaser.yml
=> chore(goreleaser): filter changelog commits

.github/workflows/publish.yml
=> chore(ci): fix aur publisher

Makefile, README.md, internal/terminal/resizeevents.go
- make terminal helpers build for freebsd, too
- update makefile and readme for freebsd as well
=> Fix: freebsd build

CHANGELOG.md
Publishing version 1.1.1 as a quickfix for API one-time-password changes.
=> Publish v1.1.1

.gitignore, internal/commands/server/show.go, internal/commands/server/show_test.go, internal/core/core.go
- disable colors on non-human output
- remove extra space after server IP
- add `.vscode` to .gitignore
=> fix(core): disable colors on non-human output

CHANGELOG.md, README.md, internal/commands/all/all.go, internal/commands/database/database.go, internal/commands/database/list.go, internal/commands/database/show.go, internal/commands/server/list.go, internal/commands/util.go, internal/completion/database.go, internal/completion/database_test.go, internal/mock/mock.go, internal/output/marshaledwithhumandetails.go, internal/output/marshaledwithhumanoutput.go, internal/output/marshaledwithhumanoutput_test.go, internal/resolver/database.go, internal/resolver/database_test.go, internal/service/service.go
```txt
$ upctl database list
UUID                                   Title                  Type   Plan                Zone      State   
────────────────────────────────────── ────────────────────── ────── ─────────────────── ───────── ─────────
09503ef9-1d0d-4874-9b23-2e3e6e2cb828   upctl-output-demo-db   pg     3x2xCPU-4GB-100GB   pl-waw1   running 
$ upctl database show upctl-output-demo-db
Overview:
UUID:    09503ef9-1d0d-4874-9b23-2e3e6e2cb828 
Title:   upctl-output-demo-db                 
Name:    output-demo                          
Type:    PostgreSQL                           
Version: 14                                   
Plan:    3x2xCPU-4GB-100GB                    
Zone:    pl-waw1                              
State:   running …
```
=> Add database list and database show commands

CHANGELOG.md, internal/commands/server/create.go, internal/commands/storage/templatize.go
Also clarify `--os` parameter usage in server create help.
=> Display UUID of created template in storage templatise output

.github/workflows/update-doc.yml
Probably best to:
1. Review this
2. Rename main branch in GitHub
3. Merge this to `main`
This will test that our pipelines for main branch work similarly that before rename.
=> Prepare update-doc pipeline for renaming master branch to main

CHANGELOG.md, internal/commands/server/create.go, internal/commands/server/create_test.go
=> fix(server): mount OS storage as virtio by default

README.md
=> Update usage output

CHANGELOG.md
=> chore(changelog): prepare release v2.1.0

CHANGELOG.md
=> chore(changelog): prepare release v2.2.0

CHANGELOG.md, internal/commands/command.go, internal/commands/database/plans.go, internal/completion/database.go, internal/completion/ipaddress.go
See individual commits for details.
=> feat: completion improvements

.pre-commit-config.yaml
Changed pre-commit-golang repo scheme to HTTPS to be in line with other repositories.
=> chore(pre-commit): https scheme for pre-commit-golang

CHANGELOG.md
=>  chore(changelog): prepare release v2.4.0

.github/workflows/publish.yml, .goreleaser.yaml, CHANGELOG.md, Makefile, RELEASING.md
Prepares the release & updates goreleaser config to latest schema.
=> chore: prepare release v2.9.1

CHANGELOG.md, go.mod, go.sum, internal/commands/kubernetes/create.go, internal/commands/kubernetes/create_test.go, internal/commands/kubernetes/show.go, internal/commands/kubernetes/show_test.go, internal/commands/kubernetes/versions.go, internal/commands/kubernetes/versions_test.go, internal/completion/kubernetes.go, internal/mock/mock.go
Also adds version to output of `kubernetes show`.
=> feat(kubernetes): add `--version` parameter to `kubernetes create` command

.ci/docs/generate_dynamic_nav.py, .ci/docs/prepare_info_texts_for_mkdocs.py, .gitignore, Makefile, README.md, examples/README.md, examples/create_a_custom_template.md, examples/create_and_ssh_into_a_server.md, examples/possible_exit_codes.md, mkdocs.base.yaml
=> chore(examples): add more usage examples

CHANGELOG.md, internal/commands/network/create_test.go, internal/commands/network/modify_test.go, internal/commands/network/network.go
=> fix(network): do not return error on valid `dhcp-default-route` values

CHANGELOG.md, internal/commands/server/list.go, internal/commands/server/list_test.go
=> fix(server): re-add `--show-ip-addresses` support for machine output

.github/workflows/lint.yml
Update docs without triggering linters :-)
=> chore(ci): run linting only for code changes

CHANGELOG.md, examples/create_and_ssh_into_a_server.md, examples/possible_exit_codes.md, go.mod, go.sum, internal/commands/server/create.go, internal/commands/server/create_test.go
Also enable metadata service by default when the selected (or default) template requires it.
=> feat(server): update default template to Ubuntu 24.04

internal/commands/server/firewall/create.go, internal/commands/storage/create.go, internal/commands/storage/modify.go
This PR is just makes enumerations in cli help consistent with others.
=> fixed small inconsistencies in help enumerations

internal/commands/account/permissions/list.go, internal/commands/database/index/delete.go, internal/commands/database/session/cancel.go, internal/commands/ipaddress/assign.go, internal/commands/kubernetes/create.go, internal/commands/kubernetes/nodegroup/create.go, internal/commands/kubernetes/nodegroup/delete.go, internal/commands/kubernetes/nodegroup/scale.go, internal/commands/kubernetes/nodegroup/show.go, internal/commands/network/create.go, internal/commands/partner/account/create.go, internal/commands/router/create.go, internal/commands/router/modify.go, internal/commands/server/create.go, internal/commands/server/firewall/create.go, internal/commands/server/firewall/delete.go, internal/commands/server/load.go, internal/commands/server/networkinterface/create.go, internal/commands/server/networkinterface/delete.go, internal/commands/server/networkinterface/modify.go, internal/commands/server/storage/attach.go, internal/commands/server/storage/detach.go, internal/commands/servergroup/create.go, internal/commands/servergroup/modify.go, internal/commands/storage/backup/create.go, internal/commands/storage/clone.go, internal/commands/storage/create.go, internal/commands/storage/import.go, internal/commands/storage/templatize.go, internal/commands/util.go
Panic instead. These are programming errors, occurring early at startup.
=> refactor: don't ignore errors setting up cobra flags

CHANGELOG.md, go.mod, go.sum, internal/config/config.go
=> feat(tokens): add bearer token auth support

.goreleaser.yaml
* https://goreleaser.com/deprecations#snapshotname_template
* https://goreleaser.com/deprecations#archivesformat
* https://goreleaser.com/deprecations#archivesformat_overridesformat
=> chore(goreleaser): avoid deprecation warnings

internal/commands/account/token/list.go, internal/commands/account/token/list_test.go
Make it match that of the header, and be consistent with other list views.
=> fix(account): token list column order

.github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
=> chore(ci): enable dependabot version updates

.github/workflows/scorecard.yml, README.md
- https://scorecard.dev
- https://github.com/ossf/scorecard-action
=> chore(ci): add OpenSSF Scorecard

CHANGELOG.md, internal/commands/kubernetes/create.go, internal/commands/kubernetes/nodegroup/create.go, internal/commands/kubernetes/nodegroup/create_test.go
Add support for customising storage tier and size for Kubernetes node groups utilising GPU and Cloud Native plans.
=> feat(kubernetes): support storage customisation

go.mod, go.sum, internal/config/config.go
=> refactor: use credentials module for parsing secrets from keyring
