UpCloudLtd/upcloud-cli

.pre-commit-config.yaml
internal/commands/command.go
internal/commands/runcommand.go
internal/commands/server/create.go
internal/commands/server/restart.go
internal/commands/server/start.go
internal/commands/server/stop.go
internal/config/config.go
internal/core/bootstrap.go

The previous refactoring related to argument handling introduced a regression; other execution modes except the multiple/parallel mode would not create any output. 
This MR refactors how the RunE method is generated for the different types of argument handling commands. Plenty of bits were DRYed up and the separate bits have been split apart to logical pieces.

Refactor creation of command runE to unify execution of all types of commands

---

internal/commands/ipaddress/assign.go
internal/commands/ipaddress/modify.go
internal/commands/network/create.go
internal/commands/network/modify.go
internal/commands/networkinterface/create.go
internal/commands/networkinterface/modify.go
internal/commands/router/create.go
internal/commands/router/modify.go
internal/commands/server/create.go
internal/commands/server/eject.go
internal/commands/server/load.go
internal/commands/server/modify.go
internal/commands/server/restart.go
internal/commands/server/start.go
internal/commands/server/stop.go
internal/commands/serverfirewall/create.go
internal/commands/serverstorage/attach.go
internal/commands/serverstorage/detach.go
internal/commands/storage/backup_create.go
internal/commands/storage/clone.go
internal/commands/storage/create.go
internal/commands/storage/import.go
internal/commands/storage/modify.go
internal/commands/storage/templatize.go
internal/output/marshaled.go
internal/output/marshaled_test.go
internal/output/marshaledwithhumandetails.go
internal/output/render_test.go

- Rename output.Marshaled to output.MarshaledOnly to make it clear(er?) that it only outputs in marshaled outputs (even better names welcome)
- add output.MarshaledWithHumanDetails that allows us one section of details (as in output.Details) to be outputed after execution in human output mode

Add a way to return extra information in humanized output

---

.golangci.yaml
internal/commands/command.go
internal/commands/runcommand.go

This PR refactors runcommand to accept service from outside, in order to facilitate testing the runcommand logic. Previously, service was created within execute() which made it impossible to pass in mock service. 
Also makes the runcommand a bit more straightforward with less return func()s and adds the forgotten golangci config that disables just the unlambda test (which still panics with this code).

Refactor runcommand, again

---

CHANGELOG.md

This adds v0.6.0 to CHANGELOG.md and fixes "Unreleased" to point to unreleased changes again.

Add v0.6.0 to CHANGELOG

---

internal/commands/executor_test.go
internal/commands/runcommand.go
internal/commands/runcommand_test.go

Separate more bits out of the runcommand internals; move render to be called by runcommandE and move executor creation to runcommandE, as well. This is in order to separate the concerns better and make the separate bits more testable.

Refactor runcommand some more

---

internal/commands/ipaddress/assign.go

Not 100% sure, but base on usage I believe this is actually the correct description:

fix(docs): fix mac and zone flag descriptions for ip-address assign

---

internal/commands/server/create.go
internal/commands/server/create_test.go

We need to set the correct disk size:
* Classic Plan: follow the plan disk size if not overrided with custom
--os-storage-size
* Custom Plan: use OS default size if not specified over the min size allowed
(10G)

fix(storage): size up os disk to the correct value

---

internal/config/config.go
internal/core/core.go

This has been discussed before (Slack link below) and after some more thinking (wrt storage import), it seems like there really is no reason to have any sort of a default timeout in the client. 
Our backend and load balancers already enforce timeouts on the backend side and there seems to be no benefit in timing out a client request in the client end, as that will only throw errors to the users that don't really convey any useful information and will (most likely) just encourage the user to try again with a higher timeout until giving up. Hanging, on the other hand, indicates that something is wrong and requires the user to interrupt the operation manually.
In particular, local file storage imports can easily go over any sensible timeouts so the other option to support it would be to have …

fix(client-timeout): change default timeout to no timeout

---

Dockerfile
Makefile

This PR brings in a smallish Dockerfile build and creates a build step for a suitable binary. Once merged, we can have Dockerhub build a new tagged version whenever we publish one.

Dockerised version

---

internal/commands/storage/import.go
internal/commands/storage/import_test.go

Refactoring storage import to be a bit more readable and more modularized.
nb. changes the --wait flag to --no-wait, as --wait is the default.

Refactor: clean up storage import

---

go.mod
internal/commands/executor.go
internal/commands/runcommand.go
internal/output/table.go
internal/terminal/resizeevents.go
internal/terminal/resizeevents_windows.go
internal/terminal/terminal.go
internal/ui/details.go
internal/ui/log.go

- add terminal width detection 
- set up livelog rendering to respect terminal width and handle resize events (not on Windows)
Initially, the aim was to add terminal width support to table rendering as well, but it's not clear how we should handle that case as when the table does not fit, truncating the table does not seem like a good idea and when it's too small, the library used does not really give us easy ways of fitting to available width.
Thus, we just render tables like we used to - at the minimum width that we can fit the table into without truncating values.

feat: implement initial terminal width support

---

go.mod
go.sum
internal/commands/network/modify.go
internal/commands/network/modify_test.go
internal/mock/mock.go
internal/terminal/resizeevents.go

- adds a `--detach-router` toggle flag to `network modify`, that triggers a detach
- changes `--router` to only work for attaching, eg. one can't detach with `--router ""` anymore. (nb. due to the go-api issue, it didnt work before)
Considered adding separate commands for detaching and attaching, but did not like the approach as `network detachrouter` is a bit clunky? Other suggestions for improving/changing UI are welcome.

fix(network/router): implement router attaching and detaching with new go-api

---

internal/commands/networkinterface/create.go
internal/commands/networkinterface/create_test.go
internal/commands/server/create.go
internal/commands/server/create_test.go
internal/config/optionalboolean.go
internal/config/optionalboolean_test.go

* Support all network interface related attributes during server create.
Before this, a private interface couldn't be created as the network
couldn't be provided.
* Use `AddEnableDisableFlags` for bootable and source ip filtering in both
command contexts. This is to allow user to explicitly declare the intent
regardless of the API's defaults.
* Remove check for supported families per interface type from
`network-interface create` command. The limitation is a "soft" one and will
probably change. It is better to let the API handle this kind of validation.
* Remove `network` context check from `network-interface create` command.
It is supported to specify address with public and utility type of
interfaces for instance with private clouds.

feat(server): parity between server create and network-interface create commands

---

CHANGELOG.md
internal/commands/networkinterface/modify.go
internal/commands/server/create.go
internal/commands/server/create_test.go
internal/terminal/resizeevents.go

This PR will fix #97 and also address the previous insecure default of creating a password for servers. After this PR is accepted, a new version (1.1.1?) of upctl should be created.
In relation to the new [one-time password policy](https://developers.upcloud.com/1.3/8-servers/#creating-from-a-template), all deployments with both SSH keys and passwords are rejected due to the fact that one-time password would prompt for a password change for SSH logins as well, leaving the user in a nasty situation.
This PR will:
- Change the default to not creating a password
- Always creating a password when password delivery method is chosen, even if --create-password is not specified

Default to not create a password, but do so when password delivery method is chosen

---

internal/commands/storage/show.go

Storage command output has a duplicate output key "zone" used for both storage Zone and attachedToServer field,
so the server ends up in the zone field and the actual zone information is overwritten.
JSON output before:
{
...
"zone": "00088baf-d71c-4dd3-9b53-deadbabe"
}
JSON output after:
{
"server": "00088baf-d71c-4dd3-9b53-deadbabe",
"zone": "fi-hel2"
}

fix: storage command attached-to-server key overrides zone

---

CHANGELOG.md
internal/commands/runcommand.go

Previously, resolver failing (which can happen on backend failure, for example) would result in a stuttering error message:
```
cannot create resolver: cannot create resolver: ...
```
which also seems to indicate that it's a DNS issue which is problematic as the upctl internal use of 'resolver' refers to *argument* resolution rather than name resolution. This PR changes the error messages and the above error would look like:
```
cannot resolve command line arguments: cannot get resolver: ...
```

fix(resolver): clarify error messages relating to argument resolution

---

CHANGELOG.md
internal/commands/command.go
internal/commands/root/completion.go
internal/commands/root/version.go
internal/commands/runcommand_test.go

This allows running offline commands, such as upctl version, without having to define credentials.
Fixes #94

Do not create API client for offline commands

---

CHANGELOG.md
internal/commands/ipaddress/assign.go
internal/commands/ipaddress/modify.go
internal/commands/ipaddress/remove.go
internal/commands/network/create.go
internal/commands/network/delete.go
internal/commands/networkinterface/create.go
internal/commands/router/create.go
internal/commands/server/create.go
internal/commands/server/delete.go
internal/commands/server/modify.go
internal/commands/server/restart.go
internal/commands/server/start.go
internal/commands/server/stop.go
internal/commands/storage/backup_create.go
internal/commands/storage/create.go
internal/commands/storage/delete.go
internal/ui/log.go
internal/ui/log_test.go

This PR also fixes livelog rendering of quick commands (execution takes less than render tick interval) and syncs livelog formatting of related commands.

Include UUID of created resource in create output

---

CHANGELOG.md
README.md
go.mod
go.sum

Update `upcloud-go-api` to version v4.5.0.

chore(lib): update UpCloud Go API client library

---

.goreleaser.yml
README.md

`use_buildx` is deprecated in favor of the more generalist `use`.

fix(gorelease): use_buildx is deprecated

---

CHANGELOG.md
internal/commands/command.go

I set the target to `release/v1.2.0` assuming GitHub will automatically update that to `master` once #119 is merged.

Do not show usage on missing credentials error

---

CHANGELOG.md
internal/commands/server/create.go
internal/commands/server/server.go
internal/commands/server/start.go
internal/commands/server/stop.go

Script to test this:
```bash
#!/bin/bash -xe
prefix=server-wait-flag-test-
./bin/upctl server create --wait --hostname ${prefix}server --network type=public --zone pl-waw1 --ssh-keys ~/.ssh/id_ed25519.pub
sleep 15
./bin/upctl server stop --wait ${prefix}server
./bin/upctl server delete ${prefix}server
```

feat(server): add wait flag to create and stop commands

---

README.md

- Sync Mac instructions with [homebrew docs](https://formulae.brew.sh/formula/bash-completion).
- In Debian example: add `-L` to  to follow redirects, fix shell output redirect command, and remove unnecessary `chmod`.

Update Mac and Linux installation instructions

---

CHANGELOG.md
README.md
internal/commands/all/all.go
internal/commands/database/database.go
internal/commands/loadbalancer/list.go
internal/commands/loadbalancer/loadbalancer.go
internal/commands/loadbalancer/show.go
internal/commands/util.go
internal/completion/loadbalancer.go
internal/completion/loadbalancer_test.go
internal/mock/mock.go
internal/resolver/loadbalancer.go
internal/resolver/loadbalancer_test.go
internal/service/service.go

```txt
$ upctl loadbalancer list
UUID                                   Name                         Plan          Zone      State   
────────────────────────────────────── ──────────────────────────── ───────────── ───────── ─────────
0a386b02-6364-4f42-a847-5761cb1f9509   lb-module-basic-example-lb   development   pl-waw1   running 
$ upctl loadbalancer show lb-module-basic-example-lb
Overview:
UUID:              0a386b02-6364-4f42-a847-5761cb1f9509              
Name:              lb-module-basic-example-lb                        
Plan:              development                                       
Zone:              pl-waw1                                           
DNS name           lb-0a386b0263644f42a8475761cb1f9509.upcloudlb.com 
Network name …
```

Add loadbalancer list and show commands

---

CHANGELOG.md
internal/commands/database/database.go
internal/commands/loadbalancer/loadbalancer.go

Example usage:
```txt
$ upctl loadbalancer list
UUID                                   Name                         Plan          Zone      State   
────────────────────────────────────── ──────────────────────────── ───────────── ───────── ─────────
0a386b02-6364-4f42-a847-5761cb1f9509   lb-module-basic-example-lb   development   pl-waw1   running 
$ upctl lb list
UUID                                   Name                         Plan          Zone      State   
────────────────────────────────────── ──────────────────────────── ───────────── ───────── ─────────
0a386b02-6364-4f42-a847-5761cb1f9509   lb-module-basic-example-lb   development   pl-waw1   running 
```

Add db and lb aliases to database and loadbalancer, respectively

---

CHANGELOG.md
internal/commands/server/list.go
internal/commands/server/list_test.go

Implements #107 
```txt
$ upctl server list --show-ip-addresses
UUID                                   Hostname                           IP addresses                Plan        Zone      State   
────────────────────────────────────── ────────────────────────────────── ─────────────────────────── ─────────── ───────── ─────────
7e4c9a57-8cd3-40dd-85db-58fd539d213f   lb-module-basic-example-server-1   public: 10.100.10.3,        1xCPU-1GB   pl-waw1   started 
utility: 10.11.2.16                                       
01eb0dba-49aa-484e-9fde-e9fd7cadcff9   lb-module-basic-example-server-0   public: 10.100.10.4 (f),    1xCPU-1GB   pl-waw1   started 
utility: 10.11.0.199,                                     
public: 10.100.10.5 …
```

Add --show-ip-addresses flag to server list command

---

CHANGELOG.md
internal/commands/all/all.go
internal/commands/database/start.go
internal/commands/database/start_test.go
internal/commands/database/stop.go
internal/commands/database/stop_test.go
internal/mock/mock.go

Add `database connection list`, `database connection cancel`, `database start`, and `database stop` commands.

Add database start and database stop commands

---

internal/commands/all/all.go
internal/commands/storage/backup/backup.go
internal/commands/storage/backup/backup_test.go
internal/commands/storage/backup/create.go
internal/commands/storage/backup/create_test.go
internal/commands/storage/backup/restore.go
internal/commands/storage/backup/restore_test.go

This syncs directory structure with command structure similarly than with server and database commands.

Move storage backup commands into a sub-directory

---

CHANGELOG.md
README.md
cmd/upctl/main.go
internal/clierrors/client_error.go
internal/clierrors/command_failed.go
internal/commands/runcommand.go
internal/core/core.go
internal/core/core_test.go
internal/output/render.go

Script to test this:
```bash
#!/bin/bash -x
prefix=exit-codes-test-
result=0
assert_exit_code() {
actual=${1}
expected=${2}
if [ ${actual} -ne ${expected} ]; then
echo "Assert failed: got ${actual}, expected ${expected}."
result=$((result + 1))
fi
}
./bin/upctl server create
assert_exit_code $? 100
./bin/upctl server create --hostname ${prefix}vm-1 --zone pl-waw1 --ssh-keys ~/.ssh/*.pub --wait
assert_exit_code $? 0
./bin/upctl server create --hostname ${prefix}vm-2 --zone pl-waw1 --ssh-keys ~/.ssh/*.pub --wait
assert_exit_code $? 0
./bin/upctl server stop ${prefix}vm-1 --wait
assert_exit_code $? 0
./bin/upctl server stop ${prefix}vm-1 ${prefix}vm-2 --wait
assert_exit_code $? 1
./bin/upctl server stop ${prefix}vm-1 ${prefix}vm-2 --wait
assert_exit_code $? 2
./bin/upctl server delete …
```

Return non-zero exit code if command execution fails

---

CHANGELOG.md
go.mod
internal/commands/network/show.go
internal/commands/server/create.go
internal/commands/server/show.go
internal/commands/storage/show.go
internal/commands/storage/show_test.go
internal/output/combined.go
internal/output/combined_test.go
internal/output/details.go
internal/output/details_test.go
internal/output/error.go
internal/output/marshaledwithhumandetails.go
internal/output/marshaledwithhumandetails_test.go
internal/output/marshaledwithhumanoutput.go
internal/output/none.go
internal/output/onlymarshaled.go
internal/output/onlymarshaled_test.go
internal/output/output.go
internal/output/output_test.go
internal/output/raw.go
internal/output/render.go
internal/output/render_test.go
internal/output/table.go
internal/output/table_test.go
internal/output/yaml.go

Fix errors in JSON and YAML outputs

---

internal/commands/all/all.go

Add missing `loadbalancer delete` and `database delete` commands to `all.go`.

Chore: update all commands

---

CHANGELOG.md

This syncs release link targets and ordering with our other repos and with keep a changelog example.

fix(changelog): add v2.0.0 link and use compare links

---

CHANGELOG.md
internal/commands/storage/import.go
internal/commands/storage/storage.go
internal/commands/storage/templatize.go

Implements #174 and in addition:
- Add target storage info to machine readable `storage import` output
- Display UUID of created storage, if one was created, in human output of `storage import` command

 feat(storage): add `--wait` flag to import and templatise commands 

---

CHANGELOG.md
internal/commands/root/version.go

We ask OS and architecture to be included in bug reports. Outputting these in the version command makes it easier for the user to provide these.

feat(version): add OS and arch info to version output

---

.goreleaser.yml
CHANGELOG.md
Dockerfile
Dockerfile.goreleaser

This makes the `upcloud/upctl` container more suitable for usage in CI pipelines. This also adds ~5 MB (size of `alpine:3.16` vs. `scratch`) to the image size and thus the image size will be ~16 MB in total.

feat(containers): use alpine as base to have shell in our images

---

internal/commands/kubernetes/create.go
internal/commands/kubernetes/nodegroup/create.go

This is to prevent linter from panicking because of the composite type.

refactor(kubernetes): use conversion function instead of generics for node-groups

---

CHANGELOG.md
internal/commands/all/all.go
internal/commands/database/properties/format.go
internal/commands/database/properties/properties.go
internal/commands/database/properties/show.go
internal/commands/database/properties/type.go
internal/completion/database.go
internal/completion/helpers.go

Examples usage:
```
$ upctl db properties pg
Property                              Create only   Type              Example                                              
───────────────────────────────────── ───────────── ───────────────── ──────────────────────────────────────────────────────
admin_password                        yes           string or null    z66o9QXqKM                                           
admin_username                        yes           string or null    avnadmin                                             
automatic_utility_network_ip_filter   no            boolean                                                                
autovacuum_analyze_scale_factor       no            number …
```

feat(database): add command to list db properties

---

.github/workflows/publish.yml
.goreleaser.yml
CHANGELOG.md
Dockerfile
Dockerfile.goreleaser

In scripts, we recommend using `jq` for parsing values from JSON output, instead of grepping human output.

feat(containers): add `jq` to the container image and publish it also to ghcr.io

---

CHANGELOG.md
README.md
internal/commands/account/account.go
internal/commands/ipaddress/ip_address.go
internal/commands/network/network.go
internal/commands/router/router.go
internal/commands/storage/import_test.go
internal/mock/mock.go

Also adds `ip` and `net` as aliases to `ip-address` and `network` commands, respectively.

 fix: use plurals in base command help messages 

---

CHANGELOG.md
go.mod
go.sum
internal/commands/all/all.go
internal/commands/kubernetes/create.go
internal/commands/kubernetes/create_test.go
internal/commands/kubernetes/plans.go
internal/mock/mock.go

feat(kubernetes): add support for plans

---

internal/commands/kubernetes/create.go
internal/commands/kubernetes/create_test.go
internal/commands/kubernetes/nodegroup/create_test.go
internal/commands/kubernetes/show_test.go

Server plans with legacy `K8S-` prefix are not supported anymore. Removed references and updated tests.

fix(kubernetes): remove legacy plans and update help text

---

.golangci.yaml

The linter now (v2) by default blocks using any non standard library packages. Previously it did nothing as we did not have configuration file for it.

fix: remove `depguard` linter

---

README.md

Easy to miss and install an older `v1` (as indexed in [Go pkgs here](https://pkg.go.dev/github.com/UpCloudLtd/upcloud-cli)) version otherwise.

Add `go install` to README

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/test.yml
.golangci.yaml
go.mod

- Use Go 1.20
- Read Go version in `setup-go` CI step from `go.mod`
- Remove deprecated linters
- Increase timeout for linter since it seems to hit the default every now and then

chore: use Go 1.20

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Pin external Github Actions to commit SHAs [as recommended by the documentation](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

chore(ci): pin external gh actions to git sha

---

CHANGELOG.md
README.md
internal/commands/all/all.go
internal/commands/kubernetes/kubernetes.go
internal/commands/kubernetes/nodegroup/delete.go
internal/commands/kubernetes/nodegroup/nodegroup.go
internal/commands/kubernetes/nodegroup/scale.go
internal/commands/kubernetes/nodegroup/show.go
internal/commands/kubernetes/nodegroup/show_test.go
internal/commands/kubernetes/show.go
internal/commands/kubernetes/show_test.go
internal/format/kubernetes.go
internal/labels/output.go
internal/mock/mock.go

- Add `kubernetes nodegroup show` to display node-group details in tables. This also adds _Nodes_ table and _Anti-affinity_ field to human output.
- Show summary of cluster node-groups as table in `kubernetes show` output.
- Only accept single cluster as positional argument for node-group operations.
- Remove `(EXPERIMENTAL)` notices from kubernetes commands.

feat(kubernetes): add `kubernetes nodegroup show` command

---

internal/clierrors/client_error.go
internal/clierrors/command_failed.go
internal/clierrors/invalid_credentials.go
internal/clierrors/missing_credentials.go
internal/commands/command.go
internal/commands/runcommand.go
internal/config/config.go

Missing credentials
```
$ upctl server show asd
Error: user credentials not found, these must be set in config file (used /Users/kangasta/.config/upctl.yaml) or via environment variables
$ echo $?
102
```
Invalid credentials
```
$ upctl server show asd
Error: invalid user credentials, authentication failed using the given username and password
$ echo $?
103
```

fix: print cleaner error message if authentication failed

---

.github/workflows/docs.yml
.gitignore
Makefile
README.md
docs/index.md
mkdocs.base.yaml
requirements.txt

**To do:**
See [docs artifact](https://github.com/UpCloudLtd/upcloud-cli/suites/18785282537/artifacts/1094747971) from `test-docs-generator` branch to see new _Getting started_ page.

feat(docs): add getting started instructions to docs

---

CHANGELOG.md
go.mod
go.sum
internal/commands/server/create.go
internal/commands/server/create_test.go
internal/commands/server/show.go
internal/commands/server/show_test.go
internal/commands/storage/clone.go
internal/commands/storage/clone_test.go
internal/commands/storage/create.go
internal/commands/storage/create_test.go
internal/commands/storage/list.go
internal/commands/storage/list_test.go
internal/commands/storage/show.go
internal/commands/storage/show_test.go
internal/mock/mock.go

feat(storage): add encryption support

---

docs/extra.css
requirements.txt

fix(docs): overwrite colors in sidebar title

---

CHANGELOG.md
internal/commands/database/list.go
internal/commands/database/list_test.go
internal/commands/gateway/list.go
internal/commands/loadbalancer/list.go
internal/commands/objectstorage/list.go
internal/paging/paging.go

This also increases the default page size from 10 to 100.

feat: add paging flags for list commands that support paging

---

CHANGELOG.md
internal/commands/server/firewall/show_test.go
internal/commands/server/plan_list.go
internal/output/combined.go
internal/output/combined_test.go

```txt
$ upctl server plans
General purpose
Name           Cores   Memory   Storage size   Storage tier   Transfer out (GiB/month) 
────────────── ─────── ──────── ────────────── ────────────── ──────────────────────────
1xCPU-1GB          1     1024             25   maxiops                            1024 
1xCPU-2GB          1     2048             50   maxiops                            2048 
2xCPU-4GB          2     4096             80   maxiops                            4096 
4xCPU-8GB          4     8192            160   maxiops                            5120 
6xCPU-16GB         6    16384            320   maxiops                            6144 
8xCPU-32GB         8    32768            640   maxiops                            7168 
12xCPU-48GB       12    49152 …
```

refactor(server): group plans by type in `server plans` human output

---

CHANGELOG.md
internal/commands/all/all.go
internal/commands/objectstorage/regions.go
internal/format/stringslice.go

```txt
$ upctl objectstorage regions
Name       Primary zone   Zones                                                                     
────────── ────────────── ───────────────────────────────────────────────────────────────────────────
apac-1     sg-sin1        sg-sin1                                                                   
europe-1   fi-hel2        de-fra1, es-mad1, fi-hel1, fi-hel2, nl-ams1, pl-waw1, se-sto1 and uk-lon1 
```

feat(objectstorage): add command to list available regions

---

CHANGELOG.md
internal/commands/server/delete.go
internal/commands/server/restart.go
internal/commands/server/start.go
internal/commands/server/stop.go
internal/completion/server.go
internal/completion/server_test.go

We could add some more to avoid various other completions for servers let's say in `maintenance` state, but this covers the most common cases for now.

feat(server): take stopped/started state into account in completions

---

mkdocs.base.yaml

This reduces page jumping and avoids repository details animation when navigating to another page inside the documentation.

docs: enable instant navigation

---

CHANGELOG.md
internal/commands/objectstorage/delete.go
internal/commands/objectstorage/delete_test.go

Also, skip system policies when deleting policies as those can not be deleted by the user.

feat(objectstorage): add `--delete-buckets` flag to delete command

---

.pre-commit-config.yaml
CHANGELOG.md
internal/commands/database/show.go

- Adding the termination protection field to the output of upctl database list
- Removing go-lint from precommit config file

feat(dbaas): add termination_protection to upctl database show

---

internal/commands/network/network.go

Cosmetic as it's the empty string currently anyway.

fix: network family default value variable

---

.golangci.yaml

uniq-by-line moved from output to issues in [1.63.0](https://golangci-lint.run/product/changelog/#v1630).

chore(golangci-lint): avoid config deprecation warning

---

docs/index.md

In many setups, with bash-completion >= 2.12 installed, nothing needs to be done these days.

docs: update Linux bash completion setup docs

---

.github/workflows/test.yml
CHANGELOG.md
go.mod
go.sum
internal/clierrors/missing_credentials.go
internal/config/config.go
internal/config/config_test.go

This PR adds initial support for the keyring.
I used [zalando/go-keyring](https://github.com/zalando/go-keyring) because of recent commits on repo (compared to [99designs/keyring](https://github.com/99designs/keyring)).
When I say initial, I mean it's open for discussion and adding more features (create auth command and save it to keyring?).
How it works:
If a username is set and the password is empty, check the keyring for service `upctl` where the username is coming either from the config file or env.
This type of logic does not break current.
Problem:
This PR does not read the username from the keyring, so it still needs a username from config or env. Maybe to introduce a config command `--keyring` ?
For me, it works by using UPCLOUD_USERNAME and creating username/password upctl …

feat(config): added initial keyring support (#83)

---

CHANGELOG.md
go.mod
go.sum
internal/commands/kubernetes/plans.go

chore(kubernetes): remove `server_number` column and hide deprecated plans

---

.github/workflows/publish.yml
RELEASING.md
docs/index.md

This adds GitHub artifact attestations for our release binary assets. Related to and kind of an alternative to #372, I suggest we start with this.
Future improvements would be [providing attestations for Docker images](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#generating-build-provenance-for-container-images) as well, and to ["upgrade" to SLSA level 3](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-and-reusable-workflows-to-achieve-slsa-v1-build-level-3), but I think this is an ok start.
Sneak peek to the results are in my fork, https://github.com/scop/upcloud-cli/attestations
```shellsession
$ curl -fSslLO …
```

feat: release artifact attestations

---

.github/workflows/examples.yml

ci: add cleanup job to examples workflow

---

CHANGELOG.md
internal/commands/runcommand.go
internal/commands/runcommand_test.go

closes #392 
The issue:
Invalid creds returns error at [runcommand.go](https://github.com/UpCloudLtd/upcloud-cli/blob/e7fda070e023cee2c674760d1d058bbb1b0b5575/internal/commands/runcommand.go#L119) only if resolver is used.
If the resolver is not used (ex., server list), it will go into the worker queue and render an error with error output. 
This is why some commands return expected output and some just an error message.
The fix:
output the error and stop progress log to print error message as other commands do without the resolver.

fix(runcommand): output correct invalid creds error

---

examples/possible_exit_codes.md

test: validate authentication failed exit code

---

internal/commands/server/create.go
internal/commands/server/modify.go
internal/commands/server/server.go

added missing `--simple-backup` options to `upctl server create` command
_"Simple backup time in UTC, followed by daily, dailies, weeklies, or monthlies option separated by comma, or no when disabled."_
Documentation sources:
https://upcloudltd.github.io/upcloud-cli/commands_reference/upctl_server/create/
https://developers.upcloud.com/1.3/8-servers/#attributes_5

docs: add missing server create --simple-backup options

---

internal/commands/storage/show.go

```
[...]
Access:    public                               
Type:      template (cloud-init)                    
State:     online                               
[...]
```

feat: template type in storage show

---

.github/dependabot.yml

To get a fuller picture. Might not be needed once all deps have been brought up to date once.

chore(ci): bump dependabot max open gomod PR limit to 15

---

scripts/generate_aur_pkgbuild.sh

As reported here: https://aur.archlinux.org/packages/upcloud-cli#comment-1032759
The current PKGBUILD results in 
```
==> Starting package()...
/home/kainoa/.cache/yay/upcloud-cli/PKGBUILD: line 12: cd: null directory
==> ERROR: A failure occurred in package().
Aborting...
-> error making: upcloud-cli-exit status 4
```
Removing that `cd` line results in a successful installation.

fix(release): PKGBUILD null directory

---

CHANGELOG.md
examples/use_object_storage.md
internal/commands/base/base.go
internal/commands/objectstorage/accesskey/accesskey.go
internal/commands/objectstorage/accesskey/create.go
internal/commands/objectstorage/accesskey/delete.go
internal/commands/objectstorage/accesskey/list.go
internal/commands/objectstorage/bucket/bucket.go
internal/commands/objectstorage/bucket/create.go
internal/commands/objectstorage/bucket/delete.go
internal/commands/objectstorage/bucket/list.go
internal/commands/objectstorage/create.go
internal/commands/objectstorage/label/add.go
internal/commands/objectstorage/label/label.go
internal/commands/objectstorage/label/list.go
internal/commands/objectstorage/label/remove.go
internal/commands/objectstorage/list.go
internal/commands/objectstorage/network/attach.go
internal/commands/objectstorage/network/detach.go
internal/commands/objectstorage/network/list.go
internal/commands/objectstorage/network/network.go
internal/commands/objectstorage/objectstorage.go
internal/commands/objectstorage/regions.go
internal/commands/objectstorage/show.go
internal/commands/objectstorage/user/create.go
internal/commands/objectstorage/user/delete.go
internal/commands/objectstorage/user/list.go
internal/commands/objectstorage/user/user.go

- **Service Creation**: Implemented `object-storage create` command with support for:
- `--label` flag for setting labels during creation
- `--network` flag for network attachment during creation
- `--configured` flag for setting configured status
- `--wait` flag that blocks until service reaches "running" state
- **Bucket Operations**: Implemented bucket management:
- `object-storage bucket create` - Create new buckets
- `object-storage bucket delete` - Delete existing buckets
- `object-storage bucket list` - List all buckets for a service
- **Dedicated Label Commands**: Added structured label management:
- `object-storage label add` - Add labels to existing services
- `object-storage label remove` - Remove specific labels from services
- `object-storage label list` - List all labels for …

feat(obs): extend support for object storage

---

go.mod
internal/commands/storage/import_test.go

Changes:
- Bump Go version to the latest v1.25.0
- Fix a storage import test by using platform-agnostic err checks. Previously the test used a platform-specific error message. The behaviour changed in Go 1.25 due to https://go-review.googlesource.com/c/go/+/671458 and broke the test on Windows.

chore(deps): bump Go version to v1.25.0

---

CHANGELOG.md
internal/commands/account/show.go
internal/commands/account/show_test.go
internal/commands/server/plan_list.go

- New columns in "server plans" command to expose the GPU model and amount for GPU enabled plans
- New field in "account show" command to expose GPU limits
Needs #494

feat: expose GPUs in account and server plans

---

CHANGELOG.md
internal/commands/auditlog/auditlog.go
internal/commands/auditlog/export.go
internal/commands/base/base.go
internal/mock/mock.go
internal/output/raw.go
internal/output/render.go
internal/output/render_test.go
internal/service/service.go

Requires https://github.com/UpCloudLtd/upcloud-go-api/pull/377 and updated to a new upcloud-go-api release containing it.

feat: audit log export support 
